apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: newevent
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: newevent
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: newevent

  EVENT_SERVICE_URL: http://event-service:5001
  EMAIL_SERVICE_URL: http://email-service:5004
  SEATS_AVAILABLE_THRESHOLD: "10"

  CLICKHOUSE_URL: http://clickhouse:8123
  CLICKHOUSE_DB: analytics
  CLICKHOUSE_USER: default
  FLUSH_INTERVAL_MS: "5000"
  FLUSH_MAX_BUFFER: "500"

  SUPERSET_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres:5432/superset
  SUPERSET_ADMIN_USERNAME: admin
  SUPERSET_ADMIN_EMAIL: admin@example.com

  DATA_SOURCE_NAME: postgresql://postgres:postgres@postgres:5432/newevent?sslmode=disable

  GF_SECURITY_ADMIN_USER: admin

  CORS_ORIGIN: http://localhost
